### ISSUE TITLE
Check and Verify configs

### ISSUE THREAD

**Issue by Pychnight** [Pychnight/TshockRpgToolKit#62]
Ensure all plugins actually create default configs and json files if they do not exist.

- [x] Custom Npc files
-  Config File
-  NPCS json file
-  Projectiles json file
-  Invasions json file

- [x] Housing files
- Config file

- [x] Leveling files
- config file

- [x] Banking files
- Config file
- Json file
- Currency example file

- [x] Custom Skills files
- skills json file

- [x] Custom Items files
- items json file

**Comment by BlackStar26724** [comment]
Checked for all plugins. 2022_4_3
